XsisMart/XsisMart/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using XsisMart.Models;
using XsisMart.Utils;

namespace XsisMart.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly XsisMartContextModel _context;
        //private readonly IWebHostEnvironment abc;

        public CategoriesController(XsisMartContextModel context/*, IWebHostEnvironment webHostEnvironment*/)
        {
            _context = context;
            //abc = webHostEnvironment;

        }

        // GET: Categories
        public async Task<IActionResult> Index (string sortOrder,
            string currentFilter,
            string searchString,
            int? pageNumber, int? pSize)
        {
            ViewData["CurrentpSize"] = pSize;
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DescSortParm"] = sortOrder == "Desc" ? "desc_desc" : "Desc";
            ViewBag.PageSize = PaginatedList<Category>.PageSizeList();

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;
            var students = from s in _context.Categories
                           select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.NameCategory.Contains(searchString)
                                       || s.Description.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    students = students.OrderByDescending(s => s.NameCategory);
                    break;
                case "Desc":
                    students = students.OrderBy(s => s.Description);
                    break;
                case "desc_desc":
                    students = students.OrderByDescending(s => s.Description);
                    break;
                default:
                    students = students.OrderBy(s => s.NameCategory);
                    break;
            }

            int pageSize = pSize ?? 5;
            return View(await PaginatedList<Category>.CreateAsync(students, pageNumber ?? 1, pageSize));
            //return View(await students.AsNoTracking().ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.IdCategory == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdCategory,NameCategory,Description,Image")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdCategory,NameCategory,Description")] Category category)
        {
            if (id != category.IdCategory)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.IdCategory))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.IdCategory == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            _context.Categories.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.IdCategory == id);
        }    
       //[HttpPost]
       // public IActionResult OnPostMyUploader(IFormFile MyUploader)
       // {
       //     if (MyUploader != null)
       //     {
       //         var fileName = Guid.NewGuid().ToString().Replace("-", "") + Path.GetExtension(MyUploader.FileName);
       //         string uploadsFolder = Path.Combine(abc.WebRootPath, "mediaUpload");                
       //         string filePath = Path.Combine(uploadsFolder, fileName);
       //         using (var fileStream = new FileStream(filePath, FileMode.Create))
       //         {
       //             MyUploader.CopyTo(fileStream);
       //         }
       //         return Json(new { status = "success",fileName=fileName  });
       //     }
       //     return new ObjectResult(new { status = "fail" });

       // }
    }

}

XsisMart/XsisMart/Controllers/ProductController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using XsisMart.Models;
using XsisMart.Utils;
using XsisMart.ViewModels;

namespace XsisMart.Controllers
{
    public class ProductController : Controller
    {
        private readonly XsisMartContextModel _context;
        private readonly IWebHostEnvironment abc;

        public ProductController(XsisMartContextModel context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            abc = webHostEnvironment;
        }
        public async Task<IActionResult> Index(string sortOrder,
            string currentFilter,
            string searchString,
            int? pageNumber, int? pSize)
        {
            var students = from p in _context.Products
                                          join v in _context.Variants
                                          on p.IdVariant equals v.IdVariant
                                          join c in _context.Categories
                                          on v.IdCategory equals c.IdCategory
                                          select new VMProduct
                                          {
                                              IdProduct = p.IdProduct,
                                              NameProduct = p.NameProduct,
                                              Price = p.Price,
                                              Stock = p.Stock,
                                              NameCategory = c.NameCategory,
                                              NameVariant = v.NameVariant,
                                              Image=p.Image
                                          }
                                          ;

            ViewData["CurrentSort"] = sortOrder;
            ViewData["CurrentpSize"] = pSize;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["PriceSortParm"] = sortOrder == "Price" ? "price_desc" : "Price";
            ViewData["CatSortParm"] = sortOrder == "Cate" ? "Cate_desc" : "Cate";
            ViewData["VarSortParm"] = sortOrder == "Var" ? "Var_desc" : "Var";
            ViewBag.PageSize = PaginatedList<VMProduct>.PageSizeList();

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }


            ViewData["CurrentFilter"] = searchString;

            //var students = from s in list
            //               select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.NameProduct.Contains(searchString)
                                       || s.NameCategory.Contains(searchString)
                                       || s.NameVariant.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    students = students.OrderByDescending(s => s.NameProduct);
                    break;
                case "Price":
                    students = students.OrderBy(s => s.Price);
                    break;
                case "price_desc":
                    students = students.OrderByDescending(s => s.Price);
                    break;
                case "Cate":
                    students = students.OrderBy(s => s.NameCategory);
                    break;
                case "Cate_desc":
                    students = students.OrderByDescending(s => s.NameCategory);
                    break;
                case "Var":
                    students = students.OrderBy(s => s.NameVariant);
                    break;
                case "Var_desc":
                    students = students.OrderByDescending(s => s.NameVariant);
                    break;
                default:
                    students = students.OrderBy(s => s.NameProduct);
                    break;
            }
            int pageSize = pSize??5;
            
            return View(await PaginatedList<VMProduct>.CreateAsync(students, pageNumber ?? 1, pageSize) );
            //return View(students);
        }
        public  IActionResult Create()
        {
            List<Category> cd = new List<Category>();
            cd = (from c in _context.Categories select c).ToList();
            cd.Insert(0, new Category { IdCategory = 0, NameCategory = "--Select Category Name--", Description = "" });
            ViewBag.klm = cd;

            //List<Category>ListCategory = await DataCategory();
            List<Variant> cl = new List<Variant>();
            cl.Insert(0, new Variant { IdVariant = 0, NameVariant = "--Select Variant Name--", Description = "", IsDelete = false, IdCategory = 0 });

            //ViewBag.abc = ListCategory;
            ViewBag.ListVariant = cl;

            return View();

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(VMProduct _product)
        {

            if (ModelState.IsValid)
            {
                Product prodNew = new Product();
                prodNew.NameProduct = _product.NameProduct;
                prodNew.Stock = _product.Stock;
                prodNew.Price = _product.Price;
                prodNew.IdVariant = _product.IdVariant;
                prodNew.Image = _product.Image;

                _context.Add(prodNew);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            List<Category> cd = new List<Category>();
            cd = (from c in _context.Categories select c).ToList();
            cd.Insert(0, new Category { IdCategory = 0, NameCategory = "--Select Category Name--", Description = "" });
            ViewBag.klm = cd;

            //List<Category>ListCategory = await DataCategory();
            List<Variant> cl = new List<Variant>();
            cl.Insert(0, new Variant { IdVariant = 0, NameVariant = "--Select Variant Name--", Description = "", IsDelete = false, IdCategory = 0 });

            //ViewBag.abc = ListCategory;
            ViewBag.ListVariant = cl;


            return View(_product);
        }
        public async Task<IActionResult> Detail(int _IdProduct)
        {
            VMProduct list = await (from p in _context.Products
                                    join v in _context.Variants
                                    on p.IdVariant equals v.IdVariant
                                    join c in _context.Categories
                                    on v.IdCategory equals c.IdCategory
                                    select new VMProduct
                                    {
                                        IdProduct = p.IdProduct,
                                        NameProduct = p.NameProduct,
                                        Price = p.Price,
                                        Stock = p.Stock,
                                        NameCategory = c.NameCategory,
                                        NameVariant = v.NameVariant,
                                        Image=p.Image
                                    }
                                          ).FirstOrDefaultAsync(h => h.IdProduct == _IdProduct);
            if (_IdProduct == null)
            {
                return NotFound();
            }
            Product product = await _context.Products.FirstOrDefaultAsync(h => h.IdProduct == _IdProduct);
            if (product == null)
            {
                return NotFound();
            }
            return View(list);
        }
        public async Task<IActionResult> Edit(int id)
        {
            List<Category> cd = new List<Category>();
            cd = (from c in _context.Categories select c).ToList();
            cd.Insert(0, new Category { IdCategory = 0, NameCategory = "--Select Category Name--", Description = "" });
            ViewBag.klm = cd;



            List<Variant> cl = new List<Variant>();
            cl = (from d in _context.Variants select d).ToList();
            cl.Insert(0, new Variant { IdVariant = 0, NameVariant = "--Select Variant Name--", Description = "", IsDelete = false, IdCategory = 0 });

            ViewBag.ListVariant = cl;

            //ViewBag.klm = await DataCategory();


            if (id == null)
            {
                return NotFound();
            }
            VMProduct product = await DataVM(id);//buat dapetin data produk(make VM karena butuh joinan kalo gapake pakenya model)

            //var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewBag.ListVariant = await DataVariant(product.IdCategory);
            return View(product);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Product _product)
        {
            if (ModelState.IsValid)
            {
                Product prodNew = new Product();
                prodNew.NameProduct = _product.NameProduct;
                prodNew.Stock = _product.Stock;
                prodNew.Price = _product.Price;
                prodNew.IdVariant = _product.IdVariant;
                prodNew.Image = _product.Image;

                _context.Update(_product);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            List<Category> cd = new List<Category>();
            cd = (from c in _context.Categories select c).ToList();
            cd.Insert(0, new Category { IdCategory = 0, NameCategory = "--Select Category Name--", Description = "" });

XsisMart/XsisMart/Views/Shared/_Header.cshtml
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a asp-controller="Home" asp-action="Index" class="nav-link active">Home</a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="#" class="nav-link">Contact</a>
            </li>
        </ul>

        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
            <!-- Navbar Search -->
            <li class="nav-item">
                <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                    <i class="fas fa-search"></i>
                </a>
                <div class="navbar-search-block">
                    <form class="form-inline">
                        <div class="input-group input-group-sm">
                            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                            <div class="input-group-append">
                                <button class="btn btn-navbar" type="submit">
                                    <i class="fas fa-search"></i>
                                </button>
                                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                    <i class="fas fa-times"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </li>

            <!-- Messages Dropdown Menu -->
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-comments"></i>
                    <span class="badge badge-danger navbar-badge">3</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <a href="#" class="dropdown-item">
                        <!-- Message Start -->
                        <div class="media">
                            <img src="~/adminlte/dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                            <div class="media-body">
                                <h3 class="dropdown-item-title">
                                    Brad Diesel
                                    <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                                </h3>
                                <p class="text-sm">Call me whenever you can...</p>
                                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                            </div>
                        </div>
                        <!-- Message End -->
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <!-- Message Start -->
                        <div class="media">
                            <img src="~/adminlte/dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                            <div class="media-body">
                                <h3 class="dropdown-item-title">
                                    John Pierce
                                    <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                                </h3>
                                <p class="text-sm">I got your message bro</p>
                                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                            </div>
                        </div>
                        <!-- Message End -->
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <!-- Message Start -->
                        <div class="media">
                            <img src="~/adminlte/dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                            <div class="media-body">
                                <h3 class="dropdown-item-title">
                                    Nora Silvester
                                    <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                                </h3>
                                <p class="text-sm">The subject goes here</p>
                                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                            </div>
                        </div>
                        <!-- Message End -->
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
                </div>
            </li>
            <!-- Notifications Dropdown Menu -->
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-bell"></i>
                    <span class="badge badge-warning navbar-badge">15</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-item dropdown-header">15 Notifications</span>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-envelope mr-2"></i> 4 new messages
                        <span class="float-right text-muted text-sm">3 mins</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-users mr-2"></i> 8 friend requests
                        <span class="float-right text-muted text-sm">12 hours</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-file mr-2"></i> 3 new reports
                        <span class="float-right text-muted text-sm">2 days</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-action="ListCart" asp-controller="Home">
                    <i class="fas fa-cart-plus"></i>
                    <span class="badge badge-danger navbar-badge">@ViewBag.count</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-action="LogOut" asp-controller="Login">
                    <i class="fas fa-sign-out-alt"></i>
                </a>
            </li>
        </ul>
    </nav>

XsisMart/XsisMart/Views/Shared/_Sidebar.cshtml
@using Microsoft.AspNetCore.Http;

<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
        <img src="~/adminlte/dist/img/Grade_School_1_-removebg-preview.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light" asp-controller="Home" asp-action="Index">XSIS Mart</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/adminlte/dist/img/zQjxXEUz_400x400.jpg" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">@Context.Session.GetString("customername")</a>
            </div>
        </div>

        <!-- SidebarSearch Form -->
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                        <i class="fas fa-search fa-fw"></i>
                    </button>
                </div>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                with font-awesome or any other icon font library -->
                <li class="nav-item menu-open">
                    <a href="#" class="nav-link active">
                        <i class="fas fa-ellipsis-v"></i>
                        <p>
                            Menu
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-controller="Product" asp-action="Index" class="nav-link active">
                                <i class="fab fa-product-hunt"></i>
                                <p>Product</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Categories" asp-action="Index" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Category</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Variants" asp-action="Index" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Variant</p>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>