XsisMart/XsisMart/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using XsisMart.Models;
using XsisMart.Utils;
using XsisMart.ViewModels;

namespace XsisMart.Controllers
{
    public class HomeController : Controller
    {
        private readonly XsisMartContextModel _context;

        public HomeController(XsisMartContextModel context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(string sortOrder,
            string currentFilter,
            string searchString,
            int? pageNumber, int? pSize)
        {
            var students = from p in _context.Products
                           join v in _context.Variants
                           on p.IdVariant equals v.IdVariant
                           join c in _context.Categories
                           on v.IdCategory equals c.IdCategory
                           select new VMProduct
                           {
                               IdProduct = p.IdProduct,
                               NameProduct = p.NameProduct,
                               Price = p.Price,
                               Stock = p.Stock,
                               NameCategory = c.NameCategory,
                               NameVariant = v.NameVariant,
                               Image = p.Image
                           }
                                          ;

            ViewData["CurrentSort"] = sortOrder;
            ViewData["CurrentpSize"] = pSize;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["PriceSortParm"] = sortOrder == "Price" ? "price_desc" : "Price";
            ViewData["CatSortParm"] = sortOrder == "Cate" ? "Cate_desc" : "Cate";
            ViewData["VarSortParm"] = sortOrder == "Var" ? "Var_desc" : "Var";
            ViewBag.PageSize = PaginatedList<VMProduct>.PageSizeList();

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }


            ViewData["CurrentFilter"] = searchString;

            //var students = from s in list
            //               select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.NameProduct.Contains(searchString)
                                       || s.NameCategory.Contains(searchString)
                                       || s.NameVariant.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    students = students.OrderByDescending(s => s.NameProduct);
                    break;
                case "Price":
                    students = students.OrderBy(s => s.Price);
                    break;
                case "price_desc":
                    students = students.OrderByDescending(s => s.Price);
                    break;
                case "Cate":
                    students = students.OrderBy(s => s.NameCategory);
                    break;
                case "Cate_desc":
                    students = students.OrderByDescending(s => s.NameCategory);
                    break;
                case "Var":
                    students = students.OrderBy(s => s.NameVariant);
                    break;
                case "Var_desc":
                    students = students.OrderByDescending(s => s.NameVariant);
                    break;
                default:
                    students = students.OrderBy(s => s.NameProduct);
                    break;
            }
            int pageSize = pSize ?? 5;
            Countcart();
            return View(await PaginatedList<VMProduct>.CreateAsync(students, pageNumber ?? 1, pageSize));
            //return View(students);
        }
        public IActionResult Create()
        {
            List<Category> cd = new List<Category>();
            cd = (from c in _context.Categories select c).ToList();
            cd.Insert(0, new Category { IdCategory = 0, NameCategory = "--Select Category Name--", Description = "" });
            ViewBag.klm = cd;

            //List<Category>ListCategory = await DataCategory();
            List<Variant> cl = new List<Variant>();
            cl.Insert(0, new Variant { IdVariant = 0, NameVariant = "--Select Variant Name--", Description = "", IsDelete = false, IdCategory = 0 });

            //ViewBag.abc = ListCategory;
            ViewBag.ListVariant = cl;

            return View();

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(VMProduct _product)
        {

            if (ModelState.IsValid)
            {
                Product prodNew = new Product();
                prodNew.NameProduct = _product.NameProduct;
                prodNew.Stock = _product.Stock;
                prodNew.Price = _product.Price;
                prodNew.IdVariant = _product.IdVariant;

                _context.Add(prodNew);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            List<Category> cd = new List<Category>();
            cd = (from c in _context.Categories select c).ToList();
            cd.Insert(0, new Category { IdCategory = 0, NameCategory = "--Select Category Name--", Description = "" });
            ViewBag.klm = cd;

            //List<Category>ListCategory = await DataCategory();
            List<Variant> cl = new List<Variant>();
            cl.Insert(0, new Variant { IdVariant = 0, NameVariant = "--Select Variant Name--", Description = "", IsDelete = false, IdCategory = 0 });

            //ViewBag.abc = ListCategory;
            ViewBag.ListVariant = cl;


            return View(_product);
        }
        public async Task<IActionResult> Detail(int _IdProduct)
        {
            VMProduct list = await (from p in _context.Products
                                    join v in _context.Variants
                                    on p.IdVariant equals v.IdVariant
                                    join c in _context.Categories
                                    on v.IdCategory equals c.IdCategory
                                    select new VMProduct
                                    {
                                        IdProduct = p.IdProduct,
                                        NameProduct = p.NameProduct,
                                        Price = p.Price,
                                        Stock = p.Stock,
                                        NameCategory = c.NameCategory,
                                        NameVariant = v.NameVariant,
                                        Image = p.Image
                                    }
                                          ).FirstOrDefaultAsync(h => h.IdProduct == _IdProduct);
            if (_IdProduct == null)
            {
                return NotFound();
            }
            Product product = await _context.Products.FirstOrDefaultAsync(h => h.IdProduct == _IdProduct);
            if (product == null)
            {
                return NotFound();
            }
            return View(list);
        }
        public async Task<IActionResult> Edit(int id)
        {
            List<Category> cd = new List<Category>();
            cd = (from c in _context.Categories select c).ToList();
            cd.Insert(0, new Category { IdCategory = 0, NameCategory = "--Select Category Name--", Description = "" });
            ViewBag.klm = cd;



            List<Variant> cl = new List<Variant>();
            cl = (from d in _context.Variants select d).ToList();
            cl.Insert(0, new Variant { IdVariant = 0, NameVariant = "--Select Variant Name--", Description = "", IsDelete = false, IdCategory = 0 });

            ViewBag.ListVariant = cl;

            //ViewBag.klm = await DataCategory();


            if (id == null)
            {
                return NotFound();
            }
            VMTransaction product = await DataPM(id);//buat dapetin data produk(make VM karena butuh joinan kalo gapake pakenya model)

            //var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewBag.ListVariant = await DataVariant(product.IdCategory);
            return View(product);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Product _product)
        {
            if (ModelState.IsValid)
            {
                Product prodNew = new Product();
                prodNew.NameProduct = _product.NameProduct;
                prodNew.Stock = _product.Stock;
                prodNew.Price = _product.Price;
                prodNew.IdVariant = _product.IdVariant;

                _context.Update(_product);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            List<Category> cd = new List<Category>();
            cd = (from c in _context.Categories select c).ToList();
            cd.Insert(0, new Category { IdCategory = 0, NameCategory = "--Select Category Name--", Description = "" });
            ViewBag.klm = cd;

            //List<Category>ListCategory = await DataCategory();
            List<Variant> cl = new List<Variant>();
            cl.Insert(0, new Variant { IdVariant = 0, NameVariant = "--Select Variant Name--", Description = "", IsDelete = false, IdCategory = 0 });

            //ViewBag.abc = ListCategory;
            ViewBag.ListVariant = cl;
            Countcart();
            return View(_product);
        }

        public async Task<IActionResult> Delete(int id)
        {

XsisMart/XsisMart/Controllers/TransactionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using XsisMart.Models;
using XsisMart.ViewModels;

namespace XsisMart.Controllers
{
    public class TransactionController : Controller
    {
        private readonly XsisMartContextModel _context;

        public TransactionController(XsisMartContextModel context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddCart(VMTransaction trx)
        {
            try
            {
                OrderHeader header = new OrderHeader();
                OrderDetail detail = new OrderDetail();
                DateTime dt = DateTime.Now;
                int d = dt.Day;
                int m = dt.Month;
                int y = dt.Year;
                string CodeTrx = $"XM-{d}-{m}-{y}-0001";
                string LastCode = await LastCodeTransaction();

                if (LastCode != "")
                {
                    string lastString = LastCode.Substring(LastCode.Length - 4, 4);
                    int lastInt = Convert.ToInt32(lastString) + 1;
                    string joinString = "0000" + lastInt.ToString();
                    CodeTrx = $"XM-{d}-{m}-{y}-" + joinString.Substring(joinString.Length - 4, 4);
                }
                header = await _context.OrderHeaders.Where(a => a.IdCustomer == 1 && a.IsCheckout == false).FirstOrDefaultAsync();

                if (header == null)
                {
                    header = new OrderHeader();
                    header.CodeTransaction = CodeTrx;
                    //header.IdCustomer = trx.IdCustomer;
                    header.IsCheckout = false;
                    header.IdCustomer = 1;
                    _context.Add(header);
                    await _context.SaveChangesAsync();
                }

                detail.IdProduct = trx.IdProduct;
                detail.IdHeader = header.IdHeader;
                detail.Quantity = trx.Quantity;
                detail.Amount = trx.Amount;
                _context.Add(detail);
                await _context.SaveChangesAsync();

                return Json(new { status = "success" });
            }
            catch (Exception e)
            {
                return Json(new { status = "error", message = e.Message.ToString() });
            }
        }

        public async Task<string> LastCodeTransaction()
        {
            string lastNoTrx = "";
            OrderHeader data = await _context.OrderHeaders.
                                     OrderByDescending(a => a.CodeTransaction).FirstOrDefaultAsync();
            if (data != null)
            {
                lastNoTrx = data.CodeTransaction;
            }
            return lastNoTrx;
        }
        
    }
}

XsisMart/XsisMart/Views/Home/Contact.cshtml
@*

*@
@{
}

<h1> Contact </h1>

XsisMart/XsisMart/Views/Home/Delete.cshtml
@model XsisMart.ViewModels.VMTransaction

@{
    ViewData["Title"] = "Delete";
    Layout = null;
}



<div class="col-md-12">
    <!-- general form elements -->
    <div>
        <div class="card-header">
            <h5>Are you sure you want to delete this?</h5>
        </div>
        <div class="card-footer">
            <form asp-action="Delete" asp-controller="Home">
                <input type="hidden" asp-for="IdDetail" />
                <input type="submit" class="btn btn-block btn-outline-danger" value="Delete">
                <a asp-action="ListCart" class="btn btn-block btn-outline-info ">Back</a>
            </form>
        </div>
    </div>
</div>

XsisMart/XsisMart/Views/Home/Detail.cshtml
@model XsisMart.ViewModels.VMProduct
@{
    ViewData["Title"] = "Detail";
    Layout = null;
}


<section class="content">

    <!-- Default box -->
    <div class="card card-solid">
        <div class="card-body">
            <form asp-action="AddCart" asp-controller="Transaction" method="POST" id="form-transaction">
                <div class="row">
                    <div class="col-12 col-sm-6">
                        <h3 class="d-inline-block d-sm-none">LOWA Men’s Renegade GTX Mid Hiking Boots Review</h3>
                        <div class="col-12">
                            @if (Model.Image == null)
                            {
                                <img src="~/mediaUpload/f27fe425c87c497dbed14a97c3cee7ab.png" alt="" class="img-fluid" />
                            }
                            else
                            {
                                <img src="~/mediaUpload/@Model.Image" alt="" class="img-fluid" />
                            }
                        </div>
                        <div class="col-12 product-image-thumbs">
                            <div class="product-image-thumb active">
                                @if (Model.Image == null)
                                {
                                    <img src="~/mediaUpload/f27fe425c87c497dbed14a97c3cee7ab.png" alt="" class="img-fluid" />
                                }
                                else
                                {
                                    <img src="~/mediaUpload/@Model.Image" alt="" class="img-fluid" />
                                }
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6">
                        <h3 class="my-3">@Model.NameProduct</h3>
                        <p>@Model.NameVariant/@Model.NameCategory</p>

                        
                        <h4>Quantity</h4>
                        <div class="btn-group btn-group-toggle" data-toggle="buttons">
                            <input type="number" class="form-control" id="Quantity" name="Quantity" min="0">
                        </div>

                        <h4 class="mt-3">Available Stock</h4>
                        <div class="btn-group btn-group-toggle" data-toggle="buttons">
                            <h4>@Model.Stock</h4>
                        </div>

                        <div class="bg-gray py-2 px-3 mt-4">
                            <h2 class="mb-0">
                                @Model.Price
                            </h2>
                            <h4 class="mt-0">
                                <small>Ex Tax: @Model.Price </small>
                            </h4>
                        </div>

                        <div class="mt-4">                        
                            <a type="submit" id="btn-cart" class="btn btn-primary btn-lg btn-flat toastsDefaultDefault">
                            <span style="color:red;display:none" id="validateQty"></span>

                            <input type="hidden" id="Stock" name="Stock" value="@Model.Stock" />
                            <input type="hidden" id="IdProduct" name="IdProduct" value="@Model.IdProduct" />
                            <input type="hidden" id="Price" name="Price" value="@Model.Price" />
                            <span class="input-group-append">
                                <i class="fas fa-cart-plus fa-lg mr-2"></i>
                                Add to Cart
                            </span>
                            </a>

                        </div>

                        <div class="mt-4 product-share">
                            <a href="#" class="text-gray">
                                <i class="fab fa-facebook-square fa-2x"></i>
                            </a>
                            <a href="#" class="text-gray">
                                <i class="fab fa-twitter-square fa-2x"></i>
                            </a>
                            <a href="#" class="text-gray">
                                <i class="fas fa-envelope-square fa-2x"></i>
                            </a>
                            <a href="#" class="text-gray">
                                <i class="fas fa-rss-square fa-2x"></i>
                            </a>
                        </div>

                    </div>
                </div>
                <div class="row mt-4">
                    <nav class="w-100">
                        <div class="nav nav-tabs" id="product-tab" role="tablist">
                            <a class="nav-item nav-link active" id="product-desc-tab" data-toggle="tab" href="#product-desc" role="tab" aria-controls="product-desc" aria-selected="true">Description</a>                          
                        </div>
                    </nav>
                    <div class="tab-content p-3" id="nav-tabContent">
                        <div class="tab-pane fade show active" id="product-desc" role="tabpanel" aria-labelledby="product-desc-tab"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vitae condimentum erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed posuere, purus at efficitur hendrerit, augue elit lacinia arcu, a eleifend sem elit et nunc. Sed rutrum vestibulum est, sit amet cursus dolor fermentum vel. Suspendisse mi nibh, congue et ante et, commodo mattis lacus. Duis varius finibus purus sed venenatis. Vivamus varius metus quam, id dapibus velit mattis eu. Praesent et semper risus. Vestibulum erat erat, condimentum at elit at, bibendum placerat orci. Nullam gravida velit mauris, in pellentesque urna pellentesque viverra. Nullam non pellentesque justo, et ultricies neque. Praesent vel metus rutrum, tempus erat a, rutrum ante. Quisque interdum efficitur nunc vitae consectetur. Suspendisse venenatis, tortor non convallis interdum, urna mi molestie eros, vel tempor justo lacus ac justo. Fusce id enim a erat fringilla sollicitudin ultrices vel metus. </div>                    
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- /.card-body -->
    <!-- /.card -->

</section>
<!-- /.content -->



<script>

    $("#btn-cart").click(function () {
        var qty = $("#Quantity").val();
        var stock = $("#Stock").val();
        var price = $("#Price").val();

        if (qty == ""||qty=="0") {
            $("#validateQty").html('Please enter quantity')
            $("#validateQty").show();
            return false;
        }
        if (parseInt(qty) > parseInt(stock)) {
            $("#validateQty").html('Purchase over quantity')
            $("#validateQty").show();
            return false;
        }
        $("#validateQty").hide();
        var dataForm = $("#form-transaction").serialize();
        var amount = parseInt(qty) * parseInt(price)
        dataForm = dataForm + '&Amount=' + amount

        $.ajax({
            url: '/Transaction/AddCart',
            data: dataForm,
            method: 'post',
            success: function (respon) {
                if (respon.status == "success") {
                    toastr.success('Added to Cart')
                    $('#model-default').modal('hide');

                    setTimeout(function () {
                        window.location.reload();
                    }, 2000);
                }
            }
        })
    })
</script>

XsisMart/XsisMart/Views/Home/ListCart.cshtml
@model IEnumerable<XsisMart.ViewModels.VMTransaction>
@{
    ViewData["Title"] = "ListCart";
}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <form asp-action="ListCart" asp-controller="Transaction" method="POST" id="form-transaction">
                <div class="col-12">
                    <div class="callout callout-info">
                        <h5><i class="fas fa-info"></i> Note:</h5>
                        This page has been enhanced for printing. Click the print button at the bottom of the invoice to test.
                    </div>


                    <!-- Main content -->
                    <div class="invoice p-3 mb-3">
                        <!-- title row -->
                        <div class="row">
                            <div class="col-12">

                                <h4>
                                    <i class="fas fa-globe"></i> AdminLTE, Inc.
                                    <small class="float-right">Date: @ViewBag.DateNow</small>
                                </h4>
                            </div>
                            <!-- /.col -->
                        </div>
                        <!-- info row -->
                        <div class="row invoice-info">
                            <div class="col-sm-4 invoice-col">
                                From
                                <address>
                                    <strong>Admin, Inc.</strong><br>
                                    795 Folsom Ave, Suite 600<br>
                                    San Francisco, CA 94107<br>
                                    Phone: (804) 123-5432<br>
                                    Email: info@almasaeedstudio.com
                                </address>
                            </div>
                            <!-- /.col -->
                            <div class="col-sm-4 invoice-col">
                                To
                                <address>
                                    <strong>John Doe</strong><br>
                                    795 Folsom Ave, Suite 600<br>
                                    San Francisco, CA 94107<br>
                                    Phone: (555) 539-1037<br>
                                    Email: john.doe@example.com
                                </address>
                            </div>
                            <!-- /.col -->
                            <div class="col-sm-4 invoice-col">
                                <b>Invoice #007612</b><br>
                                <br>
                                <b>Order ID:</b> @ViewBag.CodeTransaction<br>
                                <b>Payment Due:</b> 2/22/2014<br>
                                <b>Account:</b> 968-34567
                            </div>

                            <!-- /.col -->
                        </div>
                        <!-- /.row -->
                        <!-- Table row -->
                        <div class="row">
                            <div class="col-12 table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>Qty</th>
                                            <th>Product</th>
                                            <th>Description</th>
                                            <th>Subtotal</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>@item.Quantity</td>
                                                <td>@item.NameProduct</td>
                                                <td>@item.NameCategory/@item.NameCategory</td>
                                                <td>@item.Amount</td>
                                                <td>
                                                    <a type="button" class="btn btn-danger btn-delete" data-id="@item.IdDetail">
                                                    <i class="fas fa-trash"></i></a>
                                                </td>
                                            </tr>

                                        }
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.col -->
                        </div>
                        <!-- /.row -->

                        <div class="row">
                            <!-- accepted payments column -->
                            <div class="col-6">
                                <p class="lead">Payment Methods:</p>
                                <img src="~/adminlte/dist/img/credit/visa.png" alt="Visa">
                                <img src="~/adminlte/dist/img/credit/mastercard.png" alt="Mastercard">
                                <img src="~/adminlte/dist/img/credit/american-express.png" alt="American Express">
                                <img src="~/adminlte/dist/img/credit/paypal2.png" alt="Paypal">

                                <p class="text-muted well well-sm shadow-none" style="margin-top: 10px;">
                                    Etsy doostang zoodles disqus groupon greplin oooj voxy zoodles, weebly ning heekya handango imeem
                                    plugg
                                    dopplr jibjab, movity jajah plickers sifteo edmodo ifttt zimbra.
                                </p>
                            </div>
                            <!-- /.col -->
                            <div class="col-6">
                                <p class="lead">Amount Due 2/22/2014</p>

                                <div class="table-responsive">
                                    <table class="table">
                                        <tbody>
                                            <tr>
                                                <th style="width:50%">Subtotal:</th>
                                                <td>@ViewBag.SubTotal</td>
                                            </tr>
                                            <tr>
                                                <th>Tax (5%)</th>
                                                <td>@ViewBag.Tax</td>
                                            </tr>
                                            <tr>
                                                <th>Shipping:</th>
                                                <td>Free</td>
                                            </tr>
                                            <tr>
                                                <th>Total:</th>
                                                <td>@ViewBag.Total</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <!-- /.col -->
                        </div>
            </form>
            <!-- /.row -->
            <!-- this row will not appear when printing -->
            <div class="row no-print">
                <div class="col-12">
                    <a href="invoice-print.html" target="_blank" class="btn btn-success float-right"><i class="fas fa-print"></i> Print</a>
                    <form asp-action="Update" asp-controller="Home" method="post" id="update-form">
                        <input type="hidden" value="@ViewBag.IdHeader" id="IdHeader" name="IdHeader" />
                        <input type="hidden" Value="@ViewBag.IdCustomer" id="IdCustomer" name="IdCustomer" />
                        <input type="hidden" Value="@ViewBag.CodeTransaction" id="CodeTransaction" name="CodeTransaction" />
                        <input type="hidden" Value="@ViewBag.IsCheckout" id="IsCheckout" name="IsCheckout" />
                        <a type="button" class="btn btn-danger btn-update">
                            <i class="far fa-credit-card btn-input"></i>
                            Submit Payment
                        </a>
                    </form>
                    <button type="button" class="btn btn-primary float-right" style="margin-right: 5px;">
                        <i class="fas fa-download"></i> Generate PDF
                    </button>
                </div>

            </div>

        </div>
                    <!-- /.invoice -->
                </div>
                <!-- /.col -->
            
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</section>

<div class="modal fade" id="modal-default">
    <div class="modal-dialog">
        <div class="modal-content bg-default">
            <div class="modal-body" id="id-body">
                <p>One fine body&hellip;</p>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
</div>

<script>
    $(".btn-delete").click(function () {
        var id = $(this).data("id");

        $("#id-body").empty();
        $("#id-body").load('/Home/Delete/' + id);
        $("#modal-default").modal("show");
    });
    $(".btn-update").click(function () {
        var id = $("#update-form").serialize();

        $.ajax({
            url: '/Home/Update/',
            dataType: 'json',
            data: id,
            method: 'post',
            success: function (respon) {
                if (respon.status == "success") {
                    toastr.success('Thanks for your order')

                    setTimeout(function () {
                        window.location.href="/Home/Index/";
                    }, 2000);
                }
                else {
                    toastr.error("error : " + respon.messages)
                }
            }
        })
    });
</script>